"use client";
import {useState} from 'react';
import {ArrowUpRight,ArrowRight,Activity,ShieldCheck,FlaskConical,Cpu,MapPin,CalendarDays,Menu,X,Check,Plus,GraduationCap,Users} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {eventConfig,tracks,programme,audiences,research,faqs,gains} from './site-data';
import {Label,Wave,LinkButton,ContactForm} from './shared';
import {partners} from './data/partners';
const nav=[['Home','home'],['About','about'],['Tracks','tracks'],['Schedule','schedule'],['Poster Challenge','research'],['Speakers','speakers'],['Who Can Attend','audience'],['Registration','registration'],['Venue','venue'],['Contact','contact']];
export default function Conclave(){const [menu,setMenu]=useState(false);const [industry,setIndustry]=useState(false);const [notice,setNotice]=useState('');function action(type:'register'|'poster',category?:string){const url=type==='register'?eventConfig.registrationUrl:eventConfig.posterUrl;if(url){window.location.assign(url);return}setNotice(type==='poster'?'Poster submissions open soon. Submission guidelines and important dates will be announced shortly.':`${category?category+': ':''}Registration details are coming soon. Applications are not open yet; fees and registration information will be announced here.`)}return <>
<a className="skip" href="#main">Skip to content</a><Navbar menu={menu} setMenu={setMenu} action={action}/>
<main id="main"><Hero action={action}/>
<section className="partner-strip" aria-label="Building a clean and high-performance sporting ecosystem">{partners.map(p=><PartnerLogo key={p.name} partner={p}/>)}<div className="strip-note"><ShieldCheck/>Building a clean & high-performance<br/>sporting ecosystem</div></section>
<section id="about" className="section light"><div className="intro-grid"><div><Label>THE CONCLAVE / 2026</Label><h2>Where sports science<br/>meets <span className="muted">human<br/>performance.</span></h2></div><div className="intro-copy"><p className="lead">Better performance begins with better understanding.</p><p>Bringing together students, researchers, coaches, sports professionals, scientists, technology experts and international institutions for two days of learning, experimentation and meaningful exchange.</p><p>Explore how nutrition, clean sport, biomechanics, performance technology, innovation, research and global knowledge exchange can enhance athlete health and human performance.</p><p>Expert-led sessions, technical demonstrations, hands-on learning, research presentations and innovation showcases come together on one multidisciplinary platform.</p><a className="text-link" href="#tracks">Find your area of exploration<ArrowRight size={18}/></a></div></div><div className="stats">{[['02','Days of learning'],['05','Integrated pillars'],['International','Knowledge exchange'],['Hands-on','Technical exposure']].map(([a,b])=><div key={a}><strong>{a}</strong><span>{b}</span></div>)}</div></section>
<section className="section why"><Label>BUILT AROUND REAL-WORLD IMPACT</Label><h2>Beyond a conference.<br/><span className="muted">A human performance experience.</span></h2><div className="feature-grid">{[{Icon:ShieldCheck,title:'Clean sport',copy:'Anti-doping awareness, athlete responsibilities and ethical practice.'},{Icon:FlaskConical,title:'Sports nutrition',copy:'Evidence-based nutrition, recovery and supplementation awareness.'},{Icon:Activity,title:'Performance technology',copy:'Explore muscle activation, movement and athlete assessment.'},{Icon:Cpu,title:'Research & innovation',copy:'Exchange ideas at the intersection of sport, science and technology.'},{Icon:Users,title:'Professional exposure',copy:'Connect with coaches, researchers and performance professionals.'}].map(({Icon,title,copy})=><article key={title}><Icon/><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
<section id="tracks" className="section dark tracks"><div className="section-top"><div><Label>FIVE PILLARS. EVERY DIMENSION.</Label><h2>Five integrated<br/><span className="cyan">experiences.</span></h2></div><p>From what fuels an athlete to global knowledge<br/>exchange. Explore performance science,<br/>research and technology from every angle.</p></div><div className="track-grid">{tracks.map((t,i)=><TrackCard key={t.title} t={t} i={i} action={action}/>)}</div></section>
<section className="section emg dark"><div><Label>THE FEATURED MASTERCLASS</Label><h2>FROM MUSCLE SIGNALS<br/>TO <span className="cyan">PERFORMANCE<br/>INSIGHTS.</span></h2><p>Modern sport increasingly depends on objective performance data. Discover how surface electromyography brings muscle activation into focus.</p><p>Explore applications in movement assessment, strength and conditioning, rehabilitation and human-performance research.</p><button className="button" onClick={()=>action('register','EMG hands-on masterclass')}>Apply for the masterclass<ArrowUpRight size={17}/></button></div><div className="emg-panel"><div className="panel-top"><span>SIGNAL EXPLORER</span><span>sEMG / CONCEPT VISUAL</span></div><Wave/><Wave className="second-wave"/><div className="signal-stages">{['Muscle activation','Signal capture','Movement analysis','Performance interpretation'].map((x,i)=><span key={x}><b>0{i+1}</b>{x}</span>)}</div><small>Educational illustration. Not a medical measurement or diagnosis.</small></div></section>
<section id="research" className="section light research"><div><Label>RESEARCH POSTER & INNOVATION CHALLENGE</Label><h2>Present.<br/>Discuss.<br/><span className="teal">Innovate.</span></h2><p>The National Sports Science Research Poster & Innovation Challenge provides an interdisciplinary platform for students, scholars and young professionals to showcase research addressing contemporary challenges in sport, health and human performance.</p><div className="proposed-awards"><span>PROPOSED RECOGNITION</span><p><b>₹10,000</b> Best Research Poster</p><p><b>₹5,000</b> Best Student Innovation</p></div><button className="button" onClick={()=>action('poster')}>Submit poster abstract<ArrowUpRight size={18}/></button><p className="fine">{eventConfig.posterDeadline?`Abstract submission deadline: ${eventConfig.posterDeadline}`:'Submission guidelines and important dates will be announced shortly.'}</p></div><div className="research-list">{research.map((r,i)=><PosterCategoryCard key={r} r={r} i={i}/>)}</div></section>
<ScheduleTimeline/>
<section id="speakers" className="section dark"><div className="section-top"><div><Label>IDEAS FROM THE PEOPLE BEHIND THE SCIENCE</Label><h2>Learn from experts.</h2></div><p>Conversations that connect academic thinking<br/>with the realities of modern sport.</p></div><div className="speaker-grid">{eventConfig.speakers.length?eventConfig.speakers.map(s=><SpeakerCard key={s.name} s={s}/>):['SPORTS SCIENCE','HUMAN PERFORMANCE','SPORTS TECHNOLOGY'].map((x,i)=><div className="speaker-placeholder" key={x}><span className="speaker-symbol">{i===0?<FlaskConical/>:i===1?<Activity/>:<Cpu/>}</span><small>{x}</small><h3>Expert speakers &<br/>resource persons</h3><span className="status-pill">To be announced</span></div>)}</div></section>
<section id="audience" className="section light"><Label>ONE PLATFORM. MANY PERSPECTIVES.</Label><h2>Built for the future of sport.</h2><p className="section-desc">If your work, study or ambition connects to human performance, you belong in this conversation.</p><div className="audience-grid">{audiences.map((a,i)=><AudienceCard key={a} a={a} i={i}/>)}</div><div className="takeaways"><h3>What you take back</h3><div>{gains.map(g=><p key={g}><Check size={17}/>{g}</p>)}</div><small>Participation / workshop certification as applicable. No certification from proposed collaborators is guaranteed.</small></div></section>
<section id="registration" className="section registration dark"><div className="section-top"><div><Label>BE PART OF WHAT’S NEXT</Label><h2>Join the conclave.</h2></div><p>25–26 November 2026<br/>Woxsen University, Hyderabad<br/><span className="status-pill">Registration now open</span></p></div><div className="registration-grid">{eventConfig.categories.map((c,i)=><RegistrationCard key={c.name} c={c} i={i} action={action}/>)}</div><p className="registration-note">Fees and inclusions are based on the current registration model and may be updated by the organising team. Accommodation and food charges apply only where stated.</p></section>
<section id="industry" className="section industry"><div><Label>SPORTS TECHNOLOGY & INDUSTRY</Label><h2>Showcase the future<br/>of sports technology.</h2><p>Organisations working in wearables, biomechanics, analytics, athlete monitoring, fitness, rehabilitation and human-performance solutions are invited to engage through demonstrations and knowledge exchange.</p><button className="button" aria-expanded={industry} onClick={()=>setIndustry(!industry)}>{industry?'Close enquiry form':'Express interest / Apply'}{industry?<X size={17}/>:<ArrowUpRight size={17}/>}</button></div><div className="industry-graphic" aria-hidden="true"><div className="radar-ring"/><div className="radar-ring inner"/><Cpu size={58}/><span>SPORT × SCIENCE × INNOVATION</span></div>{industry&&<div className="industry-form"><h3>Industry participation enquiry</h3><ContactForm industry/></div>}</section>
<section id="venue" className="section light venue"><div className="campus-gallery"><figure className="campus-placeholder"><img src={eventConfig.campusImage} alt="Woxsen University campus entrance"/><figcaption><strong>A destination for new thinking.</strong><span>WOXSEN UNIVERSITY / HYDERABAD</span></figcaption></figure><figure className="sports-photo"><img src={eventConfig.sportsFacilitiesImage} alt="Woxsen University illuminated sports facilities at night"/><figcaption>Sports facilities at Woxsen University</figcaption></figure></div><div><Label>THE VENUE</Label><h2>{eventConfig.venue}.<br/><span className="muted">{eventConfig.location}.</span></h2><p>Two days of interdisciplinary learning, research and knowledge exchange at Woxsen University.</p><p>{eventConfig.travelInformation} Organising-team contact details will be published below when confirmed.</p><LinkButton href={eventConfig.mapUrl}>Get directions</LinkButton><p className="fine">Opens Google Maps. Detailed venue and travel information coming soon.</p></div></section>
<FAQAccordion/>
<section id="contact" className="section light contact"><div><Label>LET’S START A CONVERSATION</Label><h2>Connect with the<br/>organising team.</h2><p>For participation, research, institutional groups and industry enquiries.</p><div className="contact-info"><p><b>Event coordinator</b>{eventConfig.eventCoordinator||'To be announced'}</p><p><b>Academic coordinator</b>{eventConfig.academicCoordinator||'To be announced'}</p><p><b>Email / Phone</b>{eventConfig.email||'Contact details coming soon'}{eventConfig.phone&&<><br/>{eventConfig.phone}</>}</p><p><b>Woxsen University</b>Hyderabad, India</p></div></div><ContactForm/></section>
<section className="final-cta dark"><Wave/><Label>THE NEXT LEVEL STARTS WITH UNDERSTANDING</Label><h2>THE FUTURE OF SPORT<br/>IS <span className="cyan">SCIENTIFIC.</span></h2><p>Join researchers, students, coaches, professionals and innovators<br/>shaping the next generation of human performance.</p><div className="hero-actions"><button className="button" onClick={()=>action('register')}>Register now<ArrowUpRight size={18}/></button><LinkButton secondary href="#schedule">Explore programme</LinkButton></div><small>25–26 NOVEMBER 2026 <span> / </span> WOXSEN UNIVERSITY, HYDERABAD</small></section></main>
<Footer setNotice={setNotice}/>
<Dialog open={!!notice} onOpenChange={open=>{if(!open)setNotice('')}}><DialogContent className="notice-dialog"><Label>WOXSEN CONCLAVE 2026</Label><DialogTitle>Good to know.</DialogTitle><DialogDescription>{notice}</DialogDescription><button className="button" onClick={()=>setNotice('')}>Got it<Check size={17}/></button></DialogContent></Dialog></>}

type Action=(type:"register"|"poster",category?:string)=>void;
function Navbar({menu,setMenu,action}:{menu:boolean;setMenu:(value:boolean)=>void;action:Action}){return (<header className="header"><a className="brand brand-logo" href="#home" aria-label="Woxsen University home"><img src="/logos/woxsen.png" alt="Woxsen University"/></a><nav className="desktop-nav" aria-label="Main navigation">{nav.slice(1,6).map(([label,id])=><a key={id} href={`#${id}`}>{label}</a>)}<details className="more-nav"><summary>More <Plus size={12}/></summary><div>{nav.slice(6).map(([label,id])=><a key={id} href={`#${id}`}>{label}</a>)}</div></details></nav><button className="button nav-cta" onClick={()=>action('register')}>Register now<ArrowUpRight size={15}/></button><button className="menu-toggle" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} aria-controls="mobile-nav" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button>{menu&&<nav id="mobile-nav" className="mobile-nav" aria-label="Mobile navigation">{nav.map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}<ArrowUpRight size={16}/></a>)}</nav>}</header>)}
function Hero({action}:{action:Action}){return (<section className="hero" id="home"><div className="hero-image"/><div className="hero-shade"/><div className="hero-inner"><Label>THE SCIENCE BEHIND THE NEXT LEVEL</Label><h1>INTERNATIONAL<br/>SPORTS SCIENCE<br/><span>& HUMAN<br/>PERFORMANCE</span><br/>CONCLAVE <em>2026</em></h1><p className="hero-sub">National Conclave on Clean Sport, Performance<br className="desktop-break"/> Technology, Research & Innovation</p><p className="theme">Fuel. Measure. Innovate. <b>Perform Clean.</b></p><div className="event-meta"><span><CalendarDays/>25–26 November 2026</span><span><MapPin/>{eventConfig.venue}<br/>{eventConfig.location}</span></div><div className="hero-actions"><button className="button" onClick={()=>action('register')}>Register now<ArrowUpRight size={18}/></button><LinkButton href="#about" secondary>Explore the conclave</LinkButton></div></div><div className="sensor-label"><Activity size={14}/> HUMAN PERFORMANCE LAB<span className="sensor-sub">MOVEMENT × SCIENCE × POSSIBILITY</span></div><div className="signal-card"><div><span>SURFACE EMG</span><Activity size={15}/></div><Wave/><small>ILLUSTRATIVE SIGNAL · NOT CLINICAL DATA</small></div><div className="hero-bottom"><span>02 DAYS <i/> 05 PILLARS <i/> INTERNATIONAL EXCHANGE <i/> HANDS-ON LEARNING</span><a href="#about">SCROLL TO EXPLORE <span>↓</span></a></div></section>)}
function ScheduleTimeline(){return (<section id="schedule" className="section programme"><div className="section-top"><div><Label>THE PROGRAMME</Label><h2>Two days of science,<br/>technology & performance.</h2></div><p>Science, technology and performance.<br/>A programme built to move ideas forward.<br/><span className="status-pill">Tentative programme</span></p></div><Tabs defaultValue="0"><TabsList className="day-tabs">{['25 November 2026','26 November 2026'].map((d,i)=><TabsTrigger value={String(i)} key={d}><span>DAY 0{i+1}</span>{d}<ArrowUpRight size={20}/></TabsTrigger>)}</TabsList>{programme.map((sessions,day)=><TabsContent value={String(day)} key={day}><h3 className="day-theme">{day===0?'Nutrition · Anti-Doping · Clean Sport':'Human Performance · EMG · Research · Technology'}</h3><div className="timeline">{sessions.map((p,i)=><div key={p}><span>{String(i+1).padStart(2,'0')}</span><h4>{p}</h4><span className="session-label">{i===0?'OPENING':'SESSION'}</span></div>)}</div></TabsContent>)}</Tabs></section>)}
function FAQAccordion(){return (<section className="section faq"><div><Label>BEFORE YOU JOIN</Label><h2>A few things<br/>to know.</h2><p>Have another question?</p><a className="text-link" href="#contact">Connect with the team<ArrowUpRight size={18}/></a></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<Plus size={18}/></summary><p>{a}</p></details>)}</div></section>)}
function Footer({setNotice}:{setNotice:(value:string)=>void}){return (<footer><div className="footer-top"><a href="#home" className="brand brand-logo"><img src="/logos/woxsen.png" alt="Woxsen University"/></a><p>International Sports Science & Human Performance<br/>Conclave 2026<br/>{eventConfig.date}<br/>{eventConfig.venue}, {eventConfig.location}</p><div>{nav.filter((_,i)=>![0,5,6].includes(i)).map(([n,id])=><a key={id} href={`#${id}`}>{n==='Schedule'?'Programme':n}</a>)}</div>{eventConfig.socialLinks.length>0&&<div>{eventConfig.socialLinks.map(s=><a key={s.url} href={s.url} aria-label={s.label}><ArrowUpRight size={17}/>{s.label}</a>)}</div>}</div><div className="footer-bottom"><span>© 2026 International Sports Science & Human Performance Conclave</span><div><button onClick={()=>setNotice('Privacy: This website does not store form entries directly. Registration is handled through the linked Google Form, which is governed by its own privacy terms. Google Maps is also an external service.')}>Privacy policy</button><button onClick={()=>setNotice('Terms: The programme, proposed recognition, fees, accommodation, speakers and participation arrangements may be updated by the organising team. Registration is subject to availability and the terms stated in the registration form.')}>Terms</button></div></div></footer>)}
function PartnerLogo({partner}:{partner:typeof partners[number]}){return <span className="partner-logo"><span>{partner.status.toUpperCase()}</span><img src={partner.logo} alt={partner.name}/></span>}

function TrackCard({t,i,action}:{t:typeof tracks[number];i:number;action:Action}){return (<article className={`track-card track-${i}`} key={t.title}><div className="track-art">{i===0?<div className="orbit"><ShieldCheck/></div>:i===1?<Wave/>:i===2?<div className="research-art"><span/><span/><span/><span/></div>:<div className="tech-art"><Cpu size={80}/></div>}<span className="track-no">TRACK / 0{i+1}</span></div><div className="track-copy"><small>{t.label}</small><h3>{t.title}</h3><p>{t.description}</p><details><summary>{i===3?'Explore sports technology':'Explore track'} <Plus size={17}/></summary><ul>{t.topics.map(x=><li key={x}>{x}</li>)}</ul></details>{i===2?<button className="text-link" onClick={()=>action('poster')}>Submit your research<ArrowUpRight size={17}/></button>:<button className="text-link" onClick={()=>action('register',t.title)}>Apply for this track<ArrowUpRight size={17}/></button>}</div></article>)}

function SpeakerCard({s}:{s:typeof eventConfig.speakers[number]}){return (<article key={s.name}><img src={s.photo} alt={s.name}/><h3>{s.name}</h3><p>{s.designation} · {s.organisation}</p><p>{s.expertise}</p><p>{s.sessionTitle}</p></article>)}

function RegistrationCard({c,i,action}:{c:typeof eventConfig.categories[number];i:number;action:Action}){return (<article key={c.name}><span className="category-no">0{i+1} / REGISTRATION</span><h3>{c.name}</h3><p className="registration-fee">{c.fee}</p><p className="registration-details">{c.details}</p><button className="text-link" onClick={()=>action('register',c.name)}>Register now<ArrowUpRight size={20}/></button></article>)}

function PosterCategoryCard({r,i}:{r:string;i:number}){return (<div key={r}><span>0{i+1}</span><h3>{r}</h3><ArrowUpRight size={19}/></div>)}

function AudienceCard({a,i}:{a:string;i:number}){return (<div key={a}>{i<6?<GraduationCap size={20}/>:<Users size={20}/>}<span>{a}</span></div>)}
